create table employee
(
    id       int generated by default as identity,
    name     varchar(100),
    surname  varchar(100),
    position varchar(100)
);

insert into employee (name, surname, position) values ('John', 'Johnson', 'Dev');
insert into employee (name, surname, position) values ('John1', 'Johnson1', 'Dev1')